### ISSUE TITLE
Crash in long running production process (v 2.0.13)

### ISSUE THREAD

**Issue by dyutibarma** [catamphetamine/react-website#67]
I've been running a production service on react-website 2.0.13. Over the past few months, the service has arbitrarily crashed multiple times. 

Below is the stack trace for the latest crash -

npm ERR!     /root/.npm/_logs/2018-10-22T13_43_37_029Z-debug.log
npm ERR! A complete log of this run can be found in:
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! Failed at the webpack-react-redux-isomorphic-render-example@1.0.0 production script.
npm ERR! 
npm ERR! Exit status 1
npm ERR! webpack-react-redux-isomorphic-render-example@1.0.0 production: `npm-run-all production:client:build production:client:rendering-service:build production:services`
npm ERR! errno 1
npm ERR! code ELIFECYCLE
ERROR: "production:services" exited with 1.
npm ERR!     /root/.npm/_logs/2018-10-22T13_43_36_988Z-debug.log
npm ERR! A complete log of this run can be found in:
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! Failed at the webpack-react-redux-isomorphic-render-example@1.0.0 production:services script.
npm ERR! 
npm ERR! Exit status 1
npm ERR! webpack-react-redux-isomorphic-render-example@1.0.0 production:services: `npm-run-all --parallel production:client:rendering-service production:proxy`
npm ERR! errno 1
npm ERR! code ELIFECYCLE
ERROR: "production:client:rendering-service" exited with 1.
npm ERR!     /root/.npm/_logs/2018-10-22T13_43_36_682Z-debug.log
npm ERR! A complete log of this run can be found in:
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! Failed at the webpack-react-redux-isomorphic-render-example@1.0.0 production:client:rendering-service script.
npm ERR! 
npm ERR! Exit status 1
npm ERR! webpack-react-redux-isomorphic-render-example@1.0.0 production:client:rendering-service: `better-npm-run production:client:rendering-service`
npm ERR! errno 1
npm ERR! code ELIFECYCLE
    at process._tickCallback (internal/process/next_tick.js:178:19)
    at endReadableNT (/dist/insights/node_modules/readable-stream/lib/_stream_readable.js:992:12)
    at StringStream.emit (events.js:180:13)
    at Object.onceWrapper (events.js:272:13)
    at StringStream.onEnd (/dist/insights/node_modules/multistream/index.js:119:10)
    at MultiStream._next (/dist/insights/node_modules/multistream/index.js:84:10)
    at MultiStream._gotNextStream (/dist/insights/node_modules/multistream/index.js:98:8)
    at MultiStream._forward (/dist/insights/node_modules/multistream/index.js:45:33)
    at b.Readable.read (_stream_readable.js:454:10)
    at b._read (/dist/insights/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:42:400)
    at a.read (/dist/insights/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:32:243)
    at a.render (/dist/insights/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:33:18)
    at xa (/dist/insights/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:28:493)
    at d (/dist/insights/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:27:316)
    at Compare.componentWillMount (/dist/insights/build/server/webpack:/src/pages/Compare.js:101:23)
    at Object.redirect (/dist/insights/node_modules/react-website/cjs/server redirect.js:41:14)
Error: Redirecting to undefined (this is not an error)
             ^
        var error = new Error("Redirecting to " + location.pathname + " (this is not an error)");
/dist/insights/node_modules/react-website/cjs/server redirect.js:41

Any help will be appreciated.

Meanwhile, I will be updating to v 2.0.31 and will keep this thread posted.

**Comment by catamphetamine** [comment]
Hmm, so it says "Redirecting to undefined (this is not an error)".
There's a special "redirection" error being thrown to perform a server-side redirect.
Seems that the redirection happens on "Compare" page inside `componentWillMount()`.
I don't think this is a supported way of redirection.
Currently server-side redirection seems to only be supported inside `@preload()`.
So I guess you shouldn't redirect inside `componentWillMount()` and the error won't happen.

**Comment by dyutibarma** [comment]
Got it. Thanks for your help!
